version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/html

hooks:
  BeforeInstall:
    - location: scripts/install_nginx.sh
      timeout: 60
      runas: root

  AfterInstall:
    - location: scripts/start_nginx.sh
      timeout: 30
      runas: root
