version: 0.2

phases:
  install:
    commands:
      - echo Installing NGINX
      - sudo yum update -y
      - sudo yum install nginx -y

  build:
    commands:
      - echo Build started on `date`
      - echo Nothing to build for static website

artifacts:
  files:
    - index.html
    - style.css
    - appspec.yml
    - scripts/install.sh
